services:
  - type: web
    name: fooddesk
    env: dotnet
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: dotnet ./publish/FoodDesk.WEB.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: fooddesk-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: fooddesk-db
    databaseName: fooddesk
    user: fooddesk_user
    plan: free

  - name: fooddesk-redis
    plan: free
    ipAllowList: [] 